spring.application.name=ventas-service

server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/ventas_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml


api.usuario.exists=http://localhost:8081/usuarios/%d/exists

api.catalogo.exists=http://localhost:8082/productos/%d

api.inventario.disponible=http://localhost:8083/inventarios/producto/%d/disponible

api.inventario.descontar=http://localhost:8083/inventarios/producto/%d/descontar

api.usuario.email=http://localhost:8081/usuarios/email?email=%s